# Generated by Django 4.2.27 on 2026-03-19 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SBER', 'Сбербанк'), ('T', 'Т-банк')], max_length=100, verbose_name='Название брокера')),
                ('fee', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Комиссия брокера')),
                ('exchange_fee', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Комиссия биржи')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Полное наименование')),
                ('ticker', models.CharField(max_length=20, unique=True, verbose_name='Тикер')),
                ('isin', models.CharField(blank=True, max_length=12, null=True, verbose_name='ISIN-код')),
                ('type', models.CharField(choices=[('STOCK', 'Акция'), ('BOND', 'Облигация'), ('ETF', 'ETF'), ('DERIVATIVE', 'Дериватив'), ('OTHER', 'Другое')], max_length=10, verbose_name='Тип ценной бумаги')),
                ('face_value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Номинальная стоимость')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта номинала')),
                ('lot_size', models.PositiveIntegerField(default=1, verbose_name='Размер лота')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('maturity_date', models.DateField(blank=True, null=True, verbose_name='Дата погашения')),
                ('coupon_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Купонная ставка (%)')),
                ('yield_to_maturity', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Доходность к погашению (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Ценная бумага',
                'verbose_name_plural': 'Ценные бумаги',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='SecurityTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on_dashboard', models.BooleanField(default=True, help_text='Отметьте, чтобы товар/статья отображалась на дашборде', verbose_name='Отображать на дашборде')),
                ('transaction_date', models.DateTimeField(verbose_name='Дата и время операции')),
                ('ticker', models.CharField(max_length=20, verbose_name='Тикер')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Покупка'), ('SELL', 'Продажа')], max_length=4, verbose_name='Тип операции')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество бумаг')),
                ('price_per_share', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Цена за бумагу')),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Общая сумма операции')),
                ('sell_price_per_share', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Цена продажи')),
                ('sell_quantity', models.PositiveIntegerField(verbose_name='Количество проданных бумаг')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.broker', verbose_name='Брокер')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.security', verbose_name='Ценная бумага')),
            ],
            options={
                'verbose_name': 'Операция с ценной бумагой',
                'verbose_name_plural': 'Операции с ценными бумагами',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['ticker'], name='pages_secur_ticker_72dc96_idx'),
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['isin'], name='pages_secur_isin_2399a2_idx'),
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['type'], name='pages_secur_type_e88622_idx'),
        ),
    ]
