# Generated by Django 4.2.29 on 2026-04-15 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitytransaction',
            name='user',
        ),
    ]
