# Generated by Django 4.2.27 on 2026-03-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_broker_security_securitytransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitytransaction',
            name='sell_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество проданных бумаг'),
        ),
    ]
