# Generated by Django 4.2.27 on 2026-03-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_securitytransaction_sell_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='exchange_fee',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Комиссия биржи'),
        ),
    ]
