# Generated by Django 4.2.27 on 2026-03-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_broker_exchange_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broker',
            options={'verbose_name': 'Брокер', 'verbose_name_plural': 'Брокеры'},
        ),
    ]
