# Generated by Django 4.2.29 on 2026-04-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_broker_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='security',
            name='face_value',
        ),
        migrations.RemoveField(
            model_name='securitytransaction',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='securitytransaction',
            name='price_per_share',
        ),
        migrations.RemoveField(
            model_name='securitytransaction',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='securitytransaction',
            name='ticker',
        ),
        migrations.RemoveField(
            model_name='securitytransaction',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='securitytransaction',
            name='buy_fee',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Комиссия покупки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securitytransaction',
            name='buy_price_per_share',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Цена за бумагу при покупке'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securitytransaction',
            name='buy_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество бумаг куплено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securitytransaction',
            name='planned_sell_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Планируемая цена продажи'),
        ),
        migrations.AddField(
            model_name='securitytransaction',
            name='sell_fee',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Комиссия продажи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securitytransaction',
            name='tmon_price_on_date',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Цена за бумагу TMON'),
        ),
        migrations.AlterField(
            model_name='securitytransaction',
            name='sell_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество бумаг продано'),
        ),
        migrations.AlterField(
            model_name='securitytransaction',
            name='transaction_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время операции'),
        ),
    ]
